### ISSUE TITLE
devtoolset-3-gcc i.e. gcc 4.9.x

### ISSUE THREAD

**Issue by markVnl** [redsleeve-linux/odroid#4]
Hi Jacco, long time no see how are you?

Thanx for sharing this, and I have not an Issue more a question:
Where did you find devtoolset-3-gcc i.e. gcc 4.9.x for aarch64?

Grtz mark

**Comment by gordan-bobic** [comment]
Is this of use?
https://buildlogs.centos.org/centos/7/sclo/aarch64/rh/

**Comment by markVnl** [comment]
thanx for the quick reply,

the repository for aarch64 seems to be largely empty:
https://buildlogs.centos.org/centos/7/sclo/aarch64/rh/devtoolset-3/

I will ask on the centos dev-arm mailing list too.

**Comment by jaccol** [comment]
Hi Mark,

Indeed it has been a long time.

I indeed made devtoolset-3 items for aarch64, to be able to build odroid
c2 kernels. I never shared them anywhere, but they are online here:
ftp://jacco.ligthart.nu/CentOS7/CentOS7.2_SCL_aarch64/devtoolset-3/

Hope this helps.

let's discuss off-list about doing a beer soon :)

Jacco

**Comment by markVnl** [comment]
Yes that will help and lets discuss it with a beer soon! 

I'll close it now, but will report back if the odroid-c2 kernelbuild was a success

**Comment by markVnl** [comment]
Hi, odroid-c2 kernelbuild was a success and quickly done. 

It took a while to find the time to install and use it;
All good on my odroid!

Thanx!
